env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - 4
  - 6

install:
  - npm -d install

script:
  - npm test

after_success:
  - ./node_modules/.bin/coveralls   < coverage/lcov.info || true
  - ./node_modules/.bin/codeclimate < coverage/lcov.info || true
