language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)            || true
  - npm coveralls                 < coverage/lcov.info || true
  - npm codeclimate-test-reporter < coverage/lcov.info || true
